### PR TITLE
CI / Artifact builder

### PR DESCRIPTION
**Pull request by willscott**
Add a basic dockerfile building the module

### CODE REVIEW

**Review by tchardin — APPROVED** [review]
Beautiful thanks! It's compiling dev builds rn, should we add a CI flag for --release or just make it the default?

**Comment by willscott** [comment]
verbose dev build is probably the thing we want to run against PR's.

There's probably another parallel workflow we set up once we're ready to make a release that builds and save the release build

**Comment by tchardin** [comment]
@willscott sure, I've setup the optimised build to have debug symbols anyways. Currently not getting any debug output from nginx modules beyond the nginx logs so still not sure how to take advantage

**Comment by willscott** [comment]
it looks like there's a flag we can compile nginx with as well: http://nginx.org/en/docs/debugging_log.html
worth trying that?

**Comment by tchardin** [comment]
Sorry, made a mess here, let me see if I can fix it

**Comment by willscott** [comment]
luckily it's a couple files unrelated from everything else :)

**Pull request merged**
